### ISSUE TITLE
Matching/Locating can be slow

### ISSUE THREAD

**Issue by peabnuts123** [eamodio/vscode-find-related#2]
I'd like to use this wonderful customisable extension in favour of the framework-specific extension [Ember Related Files](https://github.com/josa42/vscode-ember-related-files). So I've written some rules for Ember which I am happy to share when I've finished them. However, i've found that in my project (of >2000 files) the pattern matching / locating can run a bit slowly. As pictured:

![related-files-delay](https://user-images.githubusercontent.com/2322840/30301187-510a6390-97ad-11e7-8613-0d11c5203d5f.gif)

This is a bit of a pain. The Ember related files extension linked above does not have this delay, so I'm assuming there is some optimisation to be had.

For extra reference, here is my ruleset so far. It is also worth noting that I ONLY have this ruleset enabled, so it is only matching against these 5 rules: 

```JSON
"findrelated.rulesets": [
    {
      "name": "ember",
      "rules": [
        /* Component Templates */
        {
          "pattern": "(app)/templates/components/(.*)\\.hbs$",
          "locators": [
            "$1/components/$2.js"
          ]
        },
        /* Components */
        {
          "pattern": "(app)/components/(.*)\\.js$",
          "locators": [
            "$1/templates/components/$2.hbs"
          ]
        },
        /* Route Templates */
        {
          "pattern": "(app)/templates/(.*)\\.hbs$",
          "locators": [
            "$1/controllers/$2.js",
            "$1/routes/$2.js"
          ]
        },
        /* Routes */
        {
          "pattern": "(app)/routes/(.*)\\.js$",
          "locators": [
            "$1/templates/$2.hbs",
            "$1/controllers/$2.js"
          ]
        },
        /* Controllers */
        {
          "pattern": "(app)/controllers/(.*)\\.js$",
          "locators": [
            "$1/templates/$2.hbs",
            "$1/routes/$2.js"
          ]
        }
      ]
    }
  ]
```

**Comment by eamodio** [comment]
@peabnuts123 do you have a public repo where this is reproducible? I'd love to try some profiling, but would be great if I can see the same issues as you.

**Comment by peabnuts123** [comment]
I don't sorry, as my codebase is a for a client at work. I'm sure you can locate a significantly sized Ember project somewhere on GitHub. Conversely, I cab also test it on a project that is significantly smaller than my current one and see if it is the size or another factor making it slow.

**Comment by eamodio** [comment]
@peabnuts123 I just pushed 0.6 to the marketplace -- with any luck this will help with the perf issues. Please let me know, thanks!

**Comment by peabnuts123** [comment]
Wicked! I will check it out 😃

**Comment by peabnuts123** [comment]
Yes! It does appear to be performing perfectly now. I did also face / resolve some system performance issues around the search service since I made this issue which I'm sure had an impact too. Great job. I am definitely going to be adopting this now, would love to see something like #3 happen 😁

**Comment by eamodio** [comment]
@peabnuts123 Excellent! re: #3 -- PR's are always greatly appreciated ;)
