### ISSUE TITLE
Don't open file until selected

### ISSUE THREAD

**Issue by Peeja** [eamodio/vscode-find-related#20]
Issue Type: <b>Bug</b>

1. Open a file which has related files.
2. Run `Show Related Files`.

**Expected**: No files should have opened.
**Actual**: The first (and therefore selected) file has opened, behind the list of related files.

3. Select another related file with Up/Down or Ctrl-P/Ctrl-N.

**Expected**: No files should have opened.
**Actual**: The selected file has opened, behind the list of related files.

I think `findrelated.autoPreview` is maybe supposed to control this behavior (although I'm not certain that's what it means), but in any case, I have it set to `false` and still see this.

Extension version: 0.9.0
VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:57:51.166Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (0.61GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by tdegrunt** [comment]
Isn't this `"findrelated.autoOpen": true` ?

**Comment by eamodio** [comment]
Can you still reproduce this in the latest pre-release edition? It should not happen if you set `findrelated.autoPreview` to `false`.

You can switch to the pre-release edition, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.
