### ISSUE TITLE
Exclude current file from related files list

### ISSUE THREAD

**Issue by Peeja** [eamodio/vscode-find-related#21]
I have this custom ruleset:

```json
    {
      "name": "javascript",
      "rules": [
        {
          "pattern": "(.*?)(?:\\.(?:test|story))?\\.(?:js|ts|jsx|tsx)$",
          "locators": ["$1.{js,ts,jsx,tsx}","$1.{test,story}.{js,ts,jsx,tsx}"]
        },
      ],
    },
```

Out of a collection of related files (so far, the implementation, the test, and the Storybook stories), I'd like to be able to jump between any of them. However, by capturing them all this way, I'm also capturing the original file I'm in. To exclude the current file, I'd have to (I think) have a separate pattern for each kind of file, each with a different locator to match the other two kinds of files, which would be super verbose.

Given that there's never a reason to open the file that's already open, could the extension just leave out the current file even if the locator matches it?

**Comment by eamodio** [comment]
I believe this issue should be resolved in the latest pre-release edition. Can you please give it a try to confirm that the issue is resolved for you? Thanks!

You can switch to the pre-release edition, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.
