### ISSUE TITLE
Not sure how configuration works

### ISSUE THREAD

**Issue by diminutivesloop** [eamodio/vscode-find-related#4]
I tried configuring a simple custom ruleset for TypeScript but it didn't work as I expected. Am I misusing the configuration options somehow?
```
    "findrelated.rulesets": [
        {
            "name": "angular",
            "rules": [
                {
                    "pattern": "(.*)\\.(?:.ts)$",
                    "locators": [
                        "$1.spec.ts"
                    ]
                }
            ]
        }
    ],
    "findrelated.applyRulesets": [
        "angular"
    ]
```
 When I invoked the extension from TypeScript file I got the following output: `Rule(angular).match(src/app/shared/utilities.ts)=false (.*)\.(?:.ts)$`

**Comment by eamodio** [comment]
@diminutivesloop sorry for the delayed response -- I think the issue is with your regex. I think the pattern you want is `"(.*)\\.(?:ts)$"`

Let me know if that helps.

**Comment by diminutivesloop** [comment]
Looks like that was my mistake after all. Thanks for the help.
