### ISSUE TITLE
Files automatically opened, even though they should not

### ISSUE THREAD

**Issue by PunchyRascal** [eamodio/vscode-find-related#6]
- Find Related Files Version: 0.6.0
- VSCode Version: 1.17.1
- OS Version: win10

Found related files are automatically opened even though my settings is set like so:
```
"findrelated.rulesets": [
        {
            "name": "perlx",
            "rules": [
                {
                    "pattern": "(.*)/([a-zA-Z0-9_]*)\\.pm$",
                    "locators": ["$1/t/$2.t"]
                },
                {
                    "pattern": "(.*)/([a-zA-Z0-9_]*)\\.tt2?$",
                    "locators": ["$1/t/$2.t"]
                },
                {
                    "pattern": "(.*)/([a-zA-Z0-9_]*)\\.body$",
                    "locators": ["$1/t/$2.{sql,sqlt}"]
                }
            ]
        }
    ],
    "findrelated.autoOpen": false,
    "findrelated.applyRulesets": [
        "perlx"
    ],
    "findrelated.openPreview": false
```

Steps to Reproduce:

1. invoke related files dialog with 2 files
2. cycle the list with arrows
3. both files are opened

**Comment by eamodio** [comment]
`0.7.0` adds a `findrelated.autoPreview` setting to specify whether to automatically preview related files upon selection

**Comment by PunchyRascal** [comment]
Ok, thanks, I thought this was covered in `"findrelated.autoOpen": false` and `"findrelated.openPreview": false`
