### ISSUE TITLE
Stops working after a while

### ISSUE THREAD

**Issue by Gruntfuggly** [eamodio/vscode-find-related#7]
Firstly thanks - this is a really useful extension!

For some reason, after a while it seems to stop working though. It switches through my .h/.cpp and unit test files quite happily, but then it seems to stop working. I can't put my finger on what changes, but the short cut key no longer works, and Show Related File from the command menu does nothing either.

There is nothing in the developer tools console either.

**Comment by eamodio** [comment]
@Gruntfuggly Just released `0.7.0` please let me know if you are still seeing any issues

**Comment by Gruntfuggly** [comment]
Haven't seen any problems since the update. I'm not using it quite as much as before (not really developing code on my current project at the moment) but I think you can close this.

**Comment by eamodio** [comment]
Great - thanks!
