### ISSUE TITLE
Show excluded files

### ISSUE THREAD

**Issue by mikolino** [eamodio/vscode-find-related#9]
For transpiled languages like typescript or dart or sass it is common to hide the compiled .js/.css in the file explorer through config like:

    "files.exclude": {
        "**/*.js": { "when": "$(basename).ts" },
        "**/*.css": { "when": "$(basename).scss" }
    },

Find Related Files seems to respects this exclusion which makes it impossible to switch to the .js. Switching between js/ts is a major use case of this extension and I would like to suggest adding a setting to ignore/bypass the exclude list.

- Find Related Files Version: 0.6.0
- VSCode Version: 1.21
- OS Version: Windows 8.1

**Comment by eamodio** [comment]
`0.7.0` adds a `findrelated.ignoreExcludes` setting to specify whether to ignore file excludes when searching for related files
